### ISSUE TITLE
API keys should be private

### ISSUE THREAD

**Issue by nleeper** [pollpeterh/DwollaTP#2]
The API keys for OpenWeatherMap & Google GeoCode are in the repo.

https://github.com/pollpeterh/DwollaTP/blob/d5be02a9e05dd5e7fb74120a4e4bc1529399b12a/Weather.py#L5

https://github.com/pollpeterh/DwollaTP/blob/d5be02a9e05dd5e7fb74120a4e4bc1529399b12a/Weather.py#L9

Please alter this repo to remove both keys.

**Comment by pollpeterh** [comment]
Thanks Nick! I have removed the sensitive information from the repository and it's history. Documentation on using the API keys will be in the [README.](https://github.com/pollpeterh/DwollaTP/blob/master/README.md)
