### ISSUE TITLE
Unit tests should run in isolation

### ISSUE THREAD

**Issue by nleeper** [pollpeterh/DwollaTP#3]
The unit tests for this project should run in isolation. For example, the unit tests should be executable without an internet connection.

**Comment by pollpeterh** [comment]
Thanks Nick, the dependencies are now being mocked in the unit tests. See commit [722aec2](https://github.com/pollpeterh/DwollaTP/commit/722aec2df3d270309ace6263432207847b88c346#diff-f4bc68ff01eef7bed2f3a64cad7d37ca)
